name: Integrate

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python -m unittest --verbose
